import type { Doctor } from "../../types/doctor";

export const mockDoctors: Doctor[] = [
    {
        id: "1",
        name: "Dr. Marco Rossi",
        specialty: "Medicina Generale",
        address: "Via Roma 123",
        city: "Milano",
        rating: 4.8,
        totalReviews: 156,
        phone: "+39 02 1234567",
        email: "m.rossi@medcheck.it",
        reviews: [
            {
                id: "r1",
                patientName: "Giuseppe B.",
                rating: 5,
                comment: "Medico molto professionale e attento. Ha risolto il mio problema in poco tempo.",
                date: "2024-12-15",
            },
            {
                id: "r2",
                patientName: "Maria L.",
                rating: 5,
                comment: "Eccellente dottore, molto disponibile e competente. Lo consiglio vivamente!",
                date: "2024-12-10",
            },
        ],
    },
    {
        id: "2",
        name: "Dr.ssa Laura Bianchi",
        specialty: "Pediatria",
        address: "Corso Vittorio Emanuele 45",
        city: "Roma",
        rating: 4.9,
        totalReviews: 203,
        phone: "+39 06 7654321",
        email: "l.bianchi@medcheck.it",
        reviews: [
            {
                id: "r4",
                patientName: "Francesca M.",
                rating: 5,
                comment: "Fantastica con i bambini! Mia figlia si è trovata benissimo.",
                date: "2024-12-18",
            },
        ],
    },
    {
        id: "3",
        name: "Dr. Giovanni Verdi",
        specialty: "Cardiologia",
        address: "Piazza Garibaldi 78",
        city: "Napoli",
        rating: 4.7,
        totalReviews: 128,
        phone: "+39 081 9876543",
        email: "g.verdi@medcheck.it",
        reviews: [
            {
                id: "r7",
                patientName: "Salvatore R.",
                rating: 5,
                comment: "Cardiologo eccezionale. Mi ha seguito con grande attenzione durante tutto il percorso.",
                date: "2024-12-16",
            },
        ],
    },
    {
        id: "4",
        name: "Dr.ssa Sofia Russo",
        specialty: "Dermatologia",
        address: "Via Dante 56",
        city: "Torino",
        rating: 4.6,
        totalReviews: 94,
        phone: "+39 011 2345678",
        email: "s.russo@medcheck.it",
        reviews: [
            {
                id: "r10",
                patientName: "Chiara V.",
                rating: 5,
                comment: "Dermatologa bravissima! Ha risolto un problema che avevo da anni.",
                date: "2024-12-14",
            },
        ],
    },
    {
        id: "5",
        name: "Dr. Alessandro Ferrari",
        specialty: "Ortopedia",
        address: "Viale Europa 234",
        city: "Bologna",
        rating: 4.8,
        totalReviews: 167,
        phone: "+39 051 3456789",
        email: "a.ferrari@medcheck.it",
        reviews: [
            {
                id: "r13",
                patientName: "Paolo D.",
                rating: 5,
                comment: "Ortopedico eccellente! Mi ha operato al ginocchio e ora sto benissimo.",
                date: "2024-12-17",
            },
        ],
    },
    {
        id: "6",
        name: "Dr.ssa Martina Colombo",
        specialty: "Ginecologia",
        address: "Via Mazzini 89",
        city: "Firenze",
        rating: 4.9,
        totalReviews: 215,
        phone: "+39 055 4567890",
        email: "m.colombo@medcheck.it",
        reviews: [
            {
                id: "r16",
                patientName: "Alessia F.",
                rating: 5,
                comment: "Dottoressa fantastica, molto empatica e professionale.",
                date: "2024-12-19",
            },
        ],
    },
    {
        id: "7",
        name: "Dr. Roberto Esposito",
        specialty: "Oculistica",
        address: "Via Toledo 12",
        city: "Napoli",
        rating: 4.7,
        totalReviews: 142,
        phone: "+39 081 5556667",
        email: "r.esposito@medcheck.it",
        reviews: [
            {
                id: "r19",
                patientName: "Luigi C.",
                rating: 5,
                comment: "Visita accurata e spiegazioni chiare. Consigliato.",
                date: "2024-12-20",
            },
        ],
    },
    {
        id: "8",
        name: "Dr.ssa Elena Ricci",
        specialty: "Nutrizionista",
        address: "Corso Buenos Aires 33",
        city: "Milano",
        rating: 4.9,
        totalReviews: 189,
        phone: "+39 02 9988776",
        email: "e.ricci@medcheck.it",
        reviews: [
            {
                id: "r20",
                patientName: "Sara P.",
                rating: 5,
                comment: "Piano alimentare personalizzato e facile da seguire. Risultati ottimi!",
                date: "2024-12-18",
            },
        ],
    },
    {
        id: "9",
        name: "Dr. Andrea Romano",
        specialty: "Psicologia",
        address: "Via del Corso 150",
        city: "Roma",
        rating: 4.8,
        totalReviews: 110,
        phone: "+39 06 1122334",
        email: "a.romano@medcheck.it",
        reviews: [
            {
                id: "r21",
                patientName: "Davide M.",
                rating: 5,
                comment: "Professionista empatico e preparato. Mi sta aiutando molto.",
                date: "2024-12-15",
            },
        ],
    },
    {
        id: "10",
        name: "Dr.ssa Giulia Marino",
        specialty: "Dentista",
        address: "Via Indipendenza 5",
        city: "Bologna",
        rating: 4.9,
        totalReviews: 230,
        phone: "+39 051 9988776",
        email: "g.marino@medcheck.it",
        reviews: [
            {
                id: "r22",
                patientName: "Marco L.",
                rating: 5,
                comment: "Studio all'avanguardia e personale gentilissimo. Nessun dolore!",
                date: "2024-12-19",
            },
        ],
    },
];
